### DISCUSSION TITLE
How to make `.gitignore` as `ignorePath`?

### DISCUSSION THREAD

**Discussion by AlexWayfer** [unifiedjs/unified#209] [Q&A] [answered]
I'm using Remark lint.

Such configuration doesn't work:

```yaml
# .remarkrc.yaml
plugins:
  - remark-preset-lint-recommended
  - remark-gfm

settings:
  ignorePath: '.gitignore'
```

Variations without `settings:` or with `ignore-path` also doesn't affect the behavior.

What's wrong?
